/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project.mental;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

    }

}
